name: Run Unit Test via Pytest  
  
on: [push]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.10"]  
  
    steps:  
      - uses: actions/checkout@v3  
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}  
      - name: Setup SSH Keys and known_hosts
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<< "$-----BEGIN RSA PRIVATE KEY-----\n{{ secrets.SSH_PRIVATE_KEY }}\n-----END RSA PRIVATE KEY-----\n"
      - name: Install pdm and dependencies 
        run: |  
          python -m pip install --upgrade pdm  
          pdm install -d
          cd ..
          git clone https://github.com/drunkwcodes/mups.git
          cd mups
          pdm use -f /home/runner/work/mojopi/mojopi/.venv
          pdm install -d
          cd ../mojopi
      - name: Lint with Ruff  
        run: |  
          pip install ruff  
          ruff --format=github --target-version=py310 .  
        continue-on-error: true  
      - name: Test with pytest 
        run: |  
          pdm run coverage run -m pytest  -v -s  
      - name: Generate Coverage Report  
        run: |  
          pdm run coverage report -m