name: Run Unit Test via Pytest  
  
on: [push]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.10"]  
  
    steps:  
      - uses: actions/checkout@v3  
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}  
      - name: Install pdm and dependencies 
        run: |  
          python -m pip install --upgrade pdm  
          pdm install -d 
          pdm use -f /home/runner/work/mojopi/mojopi/.venv
          cd ..
          git clone https://github.com/drunkwcodes/mups.git
          cd mups
          pdm install -d
          cd ../mojopi
      - name: Lint with Ruff  
        run: |  
          pip install ruff  
          ruff --format=github --target-version=py310 --ignore=F401,E501 .  
        continue-on-error: true  
      - name: Test with pytest 
        run: |  
          pdm run coverage run -m pytest  -v -s  
      - name: Generate Coverage Report  
        run: |  
          pdm run coverage report -m